Class {
	#name : #MAIFS,
	#superclass : #Object,
	#category : #hboiLearningOutcomes
}

{ #category : #accessing }
MAIFS class >> lo1_Societal [
]

{ #category : #accessing }
MAIFS class >> pdrSchouw3 [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo2_IPS [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo3_dataPrep [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo4_machineTeaching [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo5_dataVisualisation [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo6_reporting [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo7_personalLeadership [
]

{ #category : #'as yet unclassified' }
MAIFS >> lo8_personalGoal [
]
